---
title: "About Me"
---

## Background

I grew up in the Bay Area of California, not particularly close to the ocean. However, I was always drawn to it, spending endless summer days at the aquarium and daydreaming about dolphins and sea stars. I always thought it was just a fun fascination, thinking I wanted to be a vet, cancer researcher, and even a musician. Once I started university, I realized maybe my fun fascination could actually be a career! I completed my undergraduate degree in Evolution, Ecology, and Biodiversity from the University of California, Davis (UCD) in 2018. While there, I explored as much biology as I could! I participated in microbiology research, learned the essentials of marine animal care working for the introductory biology course teaching lab, and conducting my own marine science research at the Bodega Marine Laboratory and through a Research Experience for Undergrads (REU) internship at the Oregon Institute of Marine Biology.

After graduation, I continued to explore all there was to offer in the marine science field. I participated in outdoor education as an AmeriCorps fellow at the Ocean Discovery Institute, and conducted lab research in toxicology monitoring with the Granite Canyon Marine Pollution Studies Lab. My interest in data science began a bit later at the Department of Water Resources in West Sacramento where I conducted data analysis for long-term monitoring projects, wrote technical reports, and where I first learned how to code. I also worked with the White Abalone Captive Breeding Program at UCD where I was able to expand my interest and skillset with data science, working with data going back to the program's inception and helping to implement clean workflows and reproducible codes. Both positions combined my newfound interest in data science and my already strong passion for environmental science, ultimately leading me to the Master of Environmental Data Science (MEDS) program. 

I hope to apply the skills I have honed with the MEDS program to meaningful work in environmental justice, restoration and conservation, and projects that can lead directly to positive change in environmental policy. 

You can read more about my work experience in my [resume](https://lsdixit.github.io/leeladixit_resume.pdf)!

## Education

**Master of Environmental Data Science (MEDS)**, Bren School of Environmental Science & Management, University of California, Santa Barbara (2026)

**B.S. Evolution, Ecology, and Biodiversity**, University of California, Davis (2018)
